spring.application.name=api

# Conexão com o PostgreSQL (container definido no docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/checkfleet
spring.datasource.username=checkfleet
spring.datasource.password=checkfleet123

# update: o Hibernate cria/ajusta as tabelas a partir das entidades (ok para PoC)
spring.jpa.hibernate.ddl-auto=update
